### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by confuser** [BePo65/license-report-recursive#21]
`npx licence-report` works perfectly, however additionally need licences of sub dependencies. I've tried a few variations to get this to run but not having much luck.

`npx license-report-recursive --recurse`
`npx --package license-report-recursive -- license-report --recurse`
`npx --package=license-report-recursive -c 'license-report --recurse'`
`npx --package=license-report-recursive -c 'license-report --recurse --output=csv --csvHeaders'`

Nothing outputs to stdout

**Comment by BePo65** [comment]
oh, somehow I goofed the publishing to npm. Working on the problem and report here as soon as everything is ok again.

**Comment by BePo65** [comment]
ok, I fixed.

The problem was that a one of the last actions, I added a super clever postinstall script that updates the version number of license-report in the readme.md file. But this script also runs, when you try to install 'license-report-recursive' or run it via npx. Ups 😃 

So now I added a build script that creates a dist forlder used for publishing to npm. Here I only added files needed for using the package and dropped the scripts from the package.json. Now the package should run.

**Comment by confuser** [comment]
Thanks @BePo65. Without `--recurse` it now works. However, getting a callstack error now:

```
RangeError: Maximum call stack size exceeded
    at addDependenciesRecursive (file:///Users/.../.npm/_npx/4e25a78b136288d0/node_modules/license-report-recursive/lib/addDependenciesRecursive.js:53:34)
    at async addDependenciesRecursive (file:///Users/.../.npm/_npx/4e25a78b136288d0/node_modules/license-report-recursive/lib/addDependenciesRecursive.js:52:82)
    at async file:///Users/.../.npm/_npx/4e25a78b136288d0/node_modules/license-report-recursive/index.js:67:78
```

**Comment by BePo65** [comment]
license-report v6 changed the way the license data is acquired and required a major rework of this program here.

Looks like I am not yet finished :-( I will try to solve this issue asap, but I am afraid it will take more than a few hours.

**Comment by BePo65** [comment]
Fixed the problem by switching from recursion to loops and added tests for dependency loop. The new version (6.2.0) was also released on npmjs.

I hope this will make this little program usable for you.
